### ISSUE TITLE
Fotos de satélite abiertas del terremoto de Ecuador

### ISSUE THREAD

**Issue by santiagomota** [InfoRiesgo/herramientas#4]
Fotos de satélite abiertas del terremoto de Ecuador

http://www.digitalglobeblog.com/2016/04/19/open-imagery-and-data-to-support-ecuador-earthquake-response/?utm_source=feedburner&utm_medium=email&utm_campaign=Feed%3A+digitalglobeblog+%28DigitalGlobe+blog%29

**Comment by hhkaos** [comment]
Gracias Santiago! ya lo he [añadido a las fuentes de datos](https://github.com/InfoRiesgo/herramientas/wiki/Datos) 😄
