### ISSUE TITLE
Flowminder. Terremoto de Nepal

### ISSUE THREAD

**Issue by santiagomota** [InfoRiesgo/herramientas#5]
Flowminder. Terremoto de Nepal

http://www.flowminder.org/case-studies/nepal-earthquake-2015

**Comment by hhkaos** [comment]
Gracias Santiago! clasificaríamos esta fuente como iniciativa donde se informa del impacto del desastre, ¿no?, porque datos en sí mismos no hay, ¿verdad?

**Comment by santiagomota** [comment]
Eso es Raul. 

Por cierto, para añadir mas datos. ¿Seguimos haciéndolo así o hay otra manera?

**Comment by hhkaos** [comment]
Te voy a dar permisos para que puedas añadir tú mismo la información a la wiki, ok? Aunque si para ti es más cómo así también vale 😄

**Comment by hhkaos** [comment]
[Añadido](https://github.com/InfoRiesgo/herramientas/wiki/Iniciativas)! :)

**Comment by santiagomota** [comment]
Vale. A partir de ahora intento hacerlo yo y si no puedo te pido ayuda.

**Comment by hhkaos** [comment]
Perfecto :), cualquier cosa me dices. un abrazo!
