### ISSUE TITLE
La guía visual de supervivencia de Tokio ante terremotos y otros desastres, naturales o no

### ISSUE THREAD

**Issue by santiagomota** [InfoRiesgo/herramientas#6]
La guía visual de supervivencia de Tokio ante terremotos y otros desastres, naturales o no

http://www.microsiervos.com/archivo/mundoreal/guia-visual-supervivencia-tokio-terremotos-desastres-naturales-terrorismo.html

**Comment by hhkaos** [comment]
Thx! Lo he añadido en [iniciativas](https://github.com/InfoRiesgo/herramientas/wiki/Iniciativas)
